# Generated by Django 3.2.13 on 2022-10-19 12:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foolertonApp', '0003_auto_20221010_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldetails',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicaldetails',
            name='bloodPressure',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicaldetails',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='medicaldetails',
            name='heartRate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicaldetails',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicaldetails',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
